### ISSUE TITLE
How do I reduce the window size?

### ISSUE THREAD

**Issue by sagarnibandhe** [surya-veer/movement-tracking#10]
Hello,

Hope you are doing well!

I have a question, how do we reduce the window size? when I run the script, the camera opens and takes the entire screen. How do I reduce that size?

**Comment by surya-veer** [comment]
Add this after line 75:
```
height, width = img.shape[:2]
resize = .5 # lets say 50%
img = cv2.resize(img, (int(resize*width), int(resize *height)))
```

Hope it will help.

**Comment by sagarnibandhe** [comment]
Thank you for your reply.

Where is this "src and img" coming from? When I tried adding these lines I
am getting error on both "img"(it asks me to install and import some
package) and for "src" it is giving me TypeError: Expected Ptr<cv::UMat>
for argument 'src'

Regards,
Sagar

**Comment by surya-veer** [comment]
fixed that

**Comment by sagarnibandhe** [comment]
How did you fix? what change i need to make?

**Comment by sagarnibandhe** [comment]
got it. Thank you

**Comment by sagarnibandhe** [comment]
I am getting 
Traceback (most recent call last):
  File "/Users/sagarnibandhe/PycharmProjects/movementTracking/trackmovement/move.py", line 82, in <module>
    height, width = img.shape[:2]
AttributeError: module 'img' has no attribute 'shape'

**Comment by sagarnibandhe** [comment]
This is how my code looks like:

while True:
    # Reading image from video stream
    _, img = video_capture.read()
    img = cv2.flip(img, 1)
    height, width = img.shape[:2]
    resize = .5  # lets say 50%
    img = cv2.resize(img, (resize * width, resize * height))

Error:
Traceback (most recent call last):
  File "/Users/sagarnibandhe/PycharmProjects/movementTracking/trackmovement/move.py", line 87, in <module>
    img = cv2.resize(img, (resize * width, resize * height))
TypeError: integer argument expected, got float

**Comment by surya-veer** [comment]
@sagarnibandhe this is obuous,  cv2.resize(img, (int(resize*width), int(resize *height)))

**Comment by sagarnibandhe** [comment]
@surya-veer Yes I agree. I tried this before but it doesn't reduce the window size. I have one last question, how do we handle the delay? is there any way that we can reduce the delay?
